/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectosogomez.carrillo;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
/**
 *
 * @author Alman
 */
public class Configuracion extends javax.swing.JFrame {
 Inicio inicio;
 Archivo archivo;
    /**
     * Creates new form Configuración
     */
    public Configuracion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        duracionDia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contador = new javax.swing.JTextField();
        almacenBotones = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        almacenSD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        almacenJoystick = new javax.swing.JTextField();
        almacenPantallas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        productorBotonesI = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        productorSDI = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        productorJoystickI = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        productorPantallasI = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ensambladoresI = new javax.swing.JTextField();
        productorBotonesF = new javax.swing.JTextField();
        productorJoystickF = new javax.swing.JTextField();
        productorPantallasF = new javax.swing.JTextField();
        ensambladoresF = new javax.swing.JTextField();
        productorSDF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        duracionDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionDiaActionPerformed(evt);
            }
        });

        jLabel1.setText("Duracion de los días:");

        jLabel2.setText("Dias para el despacho:");

        contador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contadorActionPerformed(evt);
            }
        });

        almacenBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almacenBotonesActionPerformed(evt);
            }
        });

        jLabel3.setText("CAPACIDAD MÁXIMA DE ALMACEN:");

        jLabel4.setText("Botones");

        jLabel5.setText("Tarjetas SD:");

        almacenSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almacenSDActionPerformed(evt);
            }
        });

        jLabel6.setText("Joysticks:");

        almacenJoystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almacenJoystickActionPerformed(evt);
            }
        });

        almacenPantallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almacenPantallasActionPerformed(evt);
            }
        });

        jLabel7.setText("Pantallas");

        jLabel8.setText("PERSONAL INCIAL:");

        jLabel9.setText("CAPACIDAD MÁXIMA DE PERSONAL:");

        productorBotonesI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productorBotonesIActionPerformed(evt);
            }
        });

        jLabel10.setText("Productor de Botones:");

        productorSDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productorSDIActionPerformed(evt);
            }
        });

        jLabel11.setText("Productor de Tarjetas SD:");

        productorJoystickI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productorJoystickIActionPerformed(evt);
            }
        });

        jLabel12.setText("Productor de  Joysticks:");

        productorPantallasI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productorPantallasIActionPerformed(evt);
            }
        });

        jLabel13.setText("Productor de  Pantallas:");

        jLabel14.setText("Ensambladores:");

        ensambladoresI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ensambladoresIActionPerformed(evt);
            }
        });

        productorBotonesF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productorBotonesFActionPerformed(evt);
            }
        });

        productorJoystickF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productorJoystickFActionPerformed(evt);
            }
        });

        productorPantallasF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productorPantallasFActionPerformed(evt);
            }
        });

        ensambladoresF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ensambladoresFActionPerformed(evt);
            }
        });

        productorSDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productorSDFActionPerformed(evt);
            }
        });

        jLabel15.setText("Productor de Botones:");

        jLabel16.setText("Productor de Tarjetas SD:");

        jLabel17.setText("Productor de  Joysticks:");

        jLabel18.setText("Productor de  Joysticks:");

        jLabel19.setText("Ensambladores:");

        jButton1.setText("Guardar Configuración");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Restaurar Configuración Estándar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel1)
                                        .addGap(27, 27, 27)
                                        .addComponent(duracionDia, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(contador, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(almacenBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel7))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(almacenSD, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(almacenJoystick, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(almacenPantallas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(productorSDI, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(productorSDF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(productorBotonesI, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(productorBotonesF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ensambladoresI, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(ensambladoresF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(productorPantallasI, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(productorPantallasF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(productorJoystickI, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(productorJoystickF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(153, 153, 153)
                                .addComponent(jLabel9)))))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(duracionDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(productorBotonesI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(productorBotonesF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(contador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productorSDI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(productorSDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productorJoystickI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(productorJoystickF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productorPantallasI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(productorPantallasF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ensambladoresI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ensambladoresF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(almacenBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(almacenSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(almacenJoystick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(almacenPantallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void duracionDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracionDiaActionPerformed

    private void contadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contadorActionPerformed

    private void almacenBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almacenBotonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_almacenBotonesActionPerformed

    private void almacenSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almacenSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_almacenSDActionPerformed

    private void almacenJoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almacenJoystickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_almacenJoystickActionPerformed

    private void almacenPantallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almacenPantallasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_almacenPantallasActionPerformed

    private void productorBotonesIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productorBotonesIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productorBotonesIActionPerformed

    private void productorSDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productorSDIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productorSDIActionPerformed

    private void productorJoystickIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productorJoystickIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productorJoystickIActionPerformed

    private void productorPantallasIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productorPantallasIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productorPantallasIActionPerformed

    private void ensambladoresIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ensambladoresIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ensambladoresIActionPerformed

    private void productorBotonesFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productorBotonesFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productorBotonesFActionPerformed

    private void productorJoystickFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productorJoystickFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productorJoystickFActionPerformed

    private void productorPantallasFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productorPantallasFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productorPantallasFActionPerformed

    private void ensambladoresFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ensambladoresFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ensambladoresFActionPerformed

    private void productorSDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productorSDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productorSDFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
       Map <String,String> config = null;
       int cont = Integer.parseInt(contador.getText());
       int duracion = Integer.parseInt(duracionDia.getText());
       int capPantalla =Integer.parseInt(almacenPantallas.getText());
       int capJoystick=Integer.parseInt(almacenJoystick.getText());
       int capBotones=Integer.parseInt(almacenBotones.getText());
       int capSD=Integer.parseInt(almacenSD.getText());
       int prodBotonesI =Integer.parseInt(productorBotonesI.getText());
       int prodPantallaI = Integer.parseInt(productorPantallasI.getText());
       int prodSDI=Integer.parseInt(productorSDI.getText());
       int prodJoystickI = Integer.parseInt(productorJoystickI.getText());
       int prodBotonesF = Integer.parseInt(productorBotonesF.getText());
       int prodPantallaF= Integer.parseInt(productorPantallasF.getText());
       int prodSDF=Integer.parseInt(productorSDF.getText());
       int prodJoystickF= Integer.parseInt(productorJoystickF.getText());
       boolean acceptable = true;
       if(prodSDI> prodSDF || prodSDF<1 || prodSDF < 0 || prodSDI < 0 ){
           acceptable = false;
           JOptionPane.showMessageDialog(null, "Los limites de los productores de tarjetas SD no son aceptables");
       }
       if(prodJoystickI > prodJoystickF || prodJoystickF <0 || prodJoystickI <0){
           acceptable = false;
           JOptionPane.showMessageDialog(null, "Los limites de los productores de joysticks no son aceptables");
       }
       if(prodBotonesI > prodBotonesF || prodBotonesF <0 || prodBotonesI <0){
           acceptable = false;
           JOptionPane.showMessageDialog(null, "Los limites de los productores de botones no son aceptables");
       }
       if(prodPantallaI > prodPantallaF || prodPantallaF <0 || prodPantallaI <0){
           acceptable = false;
           JOptionPane.showMessageDialog(null, "Los limites de los productores de pantallas no son aceptables");
       }
       if(capJoystick < 5 || capBotones < 5 || capSD < 5 || capPantalla < 5){
           acceptable = false;
           JOptionPane.showMessageDialog(null, "Capacidad de almacenamiento inválida, se debe poder almacernar lo suficiente como para poder ensamblar una consola");
       }
       if(duracion <= 0){
           acceptable = false;
           JOptionPane.showMessageDialog(null, "Duración del día niválida, no puede ser negativo o nulo");
       }
       if(cont <= 0){
           acceptable = false;
           JOptionPane.showMessageDialog(null, "cantidad de días niválida, no puede ser negativo o nulo");
       }
       if (acceptable){
       config.put("contador", contador.getText());
       config.put("duracionDia", duracionDia.getText());
       config.put("almacenBotones", almacenBotones.getText());
       config.put("almacenPantallas", almacenPantallas.getText());
       config.put("almacenJoystick", almacenJoystick.getText());
       config.put("productorBotonesI", productorBotonesI.getText());
       config.put("productorBotonesF", productorBotonesF.getText());
       config.put("productorPantallasI", productorPantallasI.getText());
       config.put("productorPantallasF", productorPantallasF.getText());
       config.put("productorJoystickI", productorJoystickI.getText());
       config.put("productorJoystickF", productorJoystickF.getText());
       config.put("productorSDI", productorSDI.getText());
       config.put("productorSDF", productorSDF.getText());
       config.put("ensambladoresI", ensambladoresI.getText());
       config.put("ensambladoresF", ensambladoresF.getText());
       archivo.saveDatafile(config);
       }
       
       }
       catch(NumberFormatException e){
       JOptionPane.showMessageDialog(null, "Por favor, solo introduzca números enteros positivos");
       }        
        this.setVisible(false);
       inicio = new Inicio();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField almacenBotones;
    private javax.swing.JTextField almacenJoystick;
    private javax.swing.JTextField almacenPantallas;
    private javax.swing.JTextField almacenSD;
    private javax.swing.JTextField contador;
    private javax.swing.JTextField duracionDia;
    private javax.swing.JTextField ensambladoresF;
    private javax.swing.JTextField ensambladoresI;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField productorBotonesF;
    private javax.swing.JTextField productorBotonesI;
    private javax.swing.JTextField productorJoystickF;
    private javax.swing.JTextField productorJoystickI;
    private javax.swing.JTextField productorPantallasF;
    private javax.swing.JTextField productorPantallasI;
    private javax.swing.JTextField productorSDF;
    private javax.swing.JTextField productorSDI;
    // End of variables declaration//GEN-END:variables
}
