/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosogomez.carrillo;

/**
 *
 * @author Alman
 */
public class Window extends javax.swing.JFrame {
static Simulacion s;

    /**
     * Creates new form Window
     */
    public Window(Simulacion s) {        
        initComponents();
        this.s = s;
        
    }
    public void setMaxcapacity(String botones, String numPantallasN, String numPantallasT, String joysticks,String lectoresSD,
            String maxProdBotones, String maxProdJoystick, String maxProdPantallas, String maxProdSD, String maxEnsamb){
    maxBotones.setText(botones);
    maxPantallasN.setText(numPantallasN);
    maxPantallasT.setText(numPantallasT);
    maxJoysticks.setText(joysticks);
    maxSD.setText(lectoresSD);
    maxEnsambladores.setText(maxEnsamb);
    maxPBotones.setText(maxProdBotones);
    maxPPantallas.setText(maxProdPantallas);
    maxPJoystick.setText(maxProdJoystick);
    maxPLectoresSD.setText(maxProdSD);
    }
    public void setJoysticks(String qjoysticks){
    joysticks.setText(qjoysticks);
    }
    public void setTarjetasSD(String SD){
    tarjetasSD.setText(SD);
    }
    public void setBotones(String numBotones){
    botones.setText(numBotones);
    }
    public void setPantallasN(String pantallas){
    pantallasN.setText(pantallas);
    }
    public void setPantallasT(String pantallas){
    pantallasT.setText(pantallas);
    }
    public void setJefe(String estado){
    jefe.setText(estado);
    }
    public void setGerente(String estado){
    gerente.setText(estado);
    }
    public void setProductorB(String productores){
    productorBotones.setText(productores);
    }
    public void setProductorSD(String productores){
    productorSD.setText(productores);
    }
    public void setProductorPantallas(String productores){
    productorPantallas.setText(productores);
    }
    public void setProductorJoystick(String productores){
    productorJoystick.setText(productores);
    }
    public void setEnsambladores(String cantEnsambladores){
    ensambladores.setText(cantEnsambladores);
    }
    public void setDays(String cantDias){
    dias.setText(cantDias);
    }
    public void setConsolas(String cant){
        consolas.setText(cant);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botones = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        joysticks = new javax.swing.JLabel();
        tarjetasSD = new javax.swing.JLabel();
        pantallasN = new javax.swing.JLabel();
        pantallasT = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dias = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jefe = new javax.swing.JLabel();
        jefe2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gerente = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Start1 = new javax.swing.JButton();
        ensambladores = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ContratarB = new javax.swing.JButton();
        productorBotones = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        productorPantallas = new javax.swing.JLabel();
        contrararPpantallas = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        productorSD = new javax.swing.JLabel();
        contratarPSD = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        productorJoystick = new javax.swing.JLabel();
        contratarPJoystick = new javax.swing.JButton();
        DespedirB = new javax.swing.JButton();
        DespedirPPantalla = new javax.swing.JButton();
        DespedirPSD = new javax.swing.JButton();
        despedirJoystick = new javax.swing.JButton();
        despedirEnsambladores = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        consolas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        maxBotones = new javax.swing.JLabel();
        maxJoysticks = new javax.swing.JLabel();
        maxSD = new javax.swing.JLabel();
        maxPantallasN = new javax.swing.JLabel();
        maxPantallasT = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        maxPBotones = new javax.swing.JLabel();
        maxPPantallas = new javax.swing.JLabel();
        maxPLectoresSD = new javax.swing.JLabel();
        maxPJoystick = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        maxEnsambladores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botones.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        botones.setText("0");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel2.setText("Botones: ");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel3.setText("Almacen: ");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel4.setText("Joysticks:");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel5.setText("Lectores SD:");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel6.setText("PantallasN:");

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel7.setText("PantallasT:");

        joysticks.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        joysticks.setText("0");

        tarjetasSD.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tarjetasSD.setText("0");

        pantallasN.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        pantallasN.setText("0");

        pantallasT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        pantallasT.setText("0");

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel8.setText("Estado del Jefe: ");

        dias.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel9.setText("DIAS PARA EL DESPLIEGUE: ");

        jefe.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jefe.setText("Desocupado");

        jefe2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jefe2.setText("Días");

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel10.setText("Estado del Gerente: ");

        gerente.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        gerente.setText("Desocupado");

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel11.setText("Nro de Ensambladores:");

        Start1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        Start1.setText("Contratar");
        Start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start1ActionPerformed(evt);
            }
        });

        ensambladores.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        ensambladores.setText("0");

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 3, 18)); // NOI18N
        jLabel12.setText("Nro de Productores de:");

        jLabel13.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel13.setText("Botones:");

        ContratarB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        ContratarB.setText("Contratar");
        ContratarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContratarBActionPerformed(evt);
            }
        });

        productorBotones.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        productorBotones.setText("0");

        jLabel14.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel14.setText("Pantallas:");

        productorPantallas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        productorPantallas.setText("0");

        contrararPpantallas.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        contrararPpantallas.setText("Contratar");
        contrararPpantallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrararPpantallasActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel15.setText("Lectores SD:");

        productorSD.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        productorSD.setText("0");

        contratarPSD.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        contratarPSD.setText("Contratar");
        contratarPSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarPSDActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel16.setText("Joysticks");

        productorJoystick.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        productorJoystick.setText("0");

        contratarPJoystick.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        contratarPJoystick.setText("Contratar");
        contratarPJoystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarPJoystickActionPerformed(evt);
            }
        });

        DespedirB.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        DespedirB.setText("Despedir");
        DespedirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DespedirBActionPerformed(evt);
            }
        });

        DespedirPPantalla.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        DespedirPPantalla.setText("Despedir");
        DespedirPPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DespedirPPantallaActionPerformed(evt);
            }
        });

        DespedirPSD.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        DespedirPSD.setText("Despedir");
        DespedirPSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DespedirPSDActionPerformed(evt);
            }
        });

        despedirJoystick.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        despedirJoystick.setText("Despedir");
        despedirJoystick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirJoystickActionPerformed(evt);
            }
        });

        despedirEnsambladores.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        despedirEnsambladores.setText("Despedir");
        despedirEnsambladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirEnsambladoresActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel17.setText("CONSOLAS PRODUCIDAS:");

        consolas.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        consolas.setText("0");

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel1.setText("/");

        jLabel18.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel18.setText("/");

        jLabel19.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel19.setText("/");

        jLabel20.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel20.setText("/");

        jLabel21.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel21.setText("/");

        maxBotones.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        maxBotones.setText("0");

        maxJoysticks.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        maxJoysticks.setText("0");

        maxSD.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        maxSD.setText("0");

        maxPantallasN.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        maxPantallasN.setText("0");

        maxPantallasT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        maxPantallasT.setText("0");

        jLabel22.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel22.setText("/");

        jLabel23.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel23.setText("/");

        jLabel24.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel24.setText("/");

        jLabel25.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel25.setText("/");

        maxPBotones.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        maxPBotones.setText("0");

        maxPPantallas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        maxPPantallas.setText("0");

        maxPLectoresSD.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        maxPLectoresSD.setText("0");

        maxPJoystick.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        maxPJoystick.setText("0");

        jLabel26.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel26.setText("/");

        maxEnsambladores.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        maxEnsambladores.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(553, 553, 553)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productorSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(productorPantallas, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                .addGap(10, 10, 10))
                            .addComponent(productorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(productorJoystick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maxPBotones, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(maxPPantallas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maxPLectoresSD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maxPJoystick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                            .addComponent(botones, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(pantallasT, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(pantallasN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tarjetasSD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(joysticks, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(4, 4, 4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(maxJoysticks, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(maxSD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(maxPantallasN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(maxPantallasT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(maxBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(24, 24, 24)
                                        .addComponent(consolas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jefe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jefe2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Start1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(despedirEnsambladores))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ensambladores, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maxEnsambladores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(contratarPSD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DespedirPSD))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(contratarPJoystick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(despedirJoystick))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(contrararPpantallas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DespedirPPantalla))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ContratarB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DespedirB)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jefe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(gerente))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ensambladores)
                            .addComponent(jLabel26)
                            .addComponent(maxEnsambladores))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(botones)
                            .addComponent(jLabel1)
                            .addComponent(maxBotones)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Start1)
                            .addComponent(despedirEnsambladores))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(joysticks)
                    .addComponent(jLabel19)
                    .addComponent(maxJoysticks))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tarjetasSD)
                    .addComponent(jLabel20)
                    .addComponent(maxSD))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pantallasN)
                    .addComponent(jLabel18)
                    .addComponent(maxPantallasN))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(pantallasT)
                            .addComponent(jLabel21)
                            .addComponent(maxPantallasT))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(consolas))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dias)
                    .addComponent(jefe2)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel12)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContratarB)
                            .addComponent(DespedirB))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contrararPpantallas)
                            .addComponent(DespedirPPantalla))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contratarPSD)
                            .addComponent(DespedirPSD))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contratarPJoystick)
                            .addComponent(despedirJoystick)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(productorBotones)
                            .addComponent(jLabel23)
                            .addComponent(maxPBotones))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(productorPantallas)
                            .addComponent(jLabel22)
                            .addComponent(maxPPantallas))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(productorSD)
                            .addComponent(jLabel24)
                            .addComponent(maxPLectoresSD))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(productorJoystick)
                            .addComponent(jLabel25)
                            .addComponent(maxPJoystick)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Start1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start1ActionPerformed
        // TODO add your handling code here:
        s.contratarEnsamblador();
    }//GEN-LAST:event_Start1ActionPerformed

    private void ContratarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContratarBActionPerformed
        s.contratarPBotones();
    }//GEN-LAST:event_ContratarBActionPerformed
       
    private void contrararPpantallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrararPpantallasActionPerformed
        s.contratarPPantalla();
    }//GEN-LAST:event_contrararPpantallasActionPerformed

    private void contratarPSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarPSDActionPerformed
        // TODO add your handling code here:
        s.contratarPSD();
    }//GEN-LAST:event_contratarPSDActionPerformed

    private void contratarPJoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarPJoystickActionPerformed
        // TODO add your handling code here:
        s.contratarPJoystick();
    }//GEN-LAST:event_contratarPJoystickActionPerformed

    private void DespedirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DespedirBActionPerformed
        // TODO add your handling code here:
        s.despedirB();
    }//GEN-LAST:event_DespedirBActionPerformed

    private void DespedirPPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DespedirPPantallaActionPerformed
        // TODO add your handling code here:
        s.despedirPantalla();
    }//GEN-LAST:event_DespedirPPantallaActionPerformed

    private void DespedirPSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DespedirPSDActionPerformed
        // TODO add your handling code here:
        s.despedirSD();
    }//GEN-LAST:event_DespedirPSDActionPerformed

    private void despedirJoystickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirJoystickActionPerformed
        // TODO add your handling code here:
        s.despedirJoystick();
    }//GEN-LAST:event_despedirJoystickActionPerformed

    private void despedirEnsambladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirEnsambladoresActionPerformed
        // TODO add your handling code here:
        s.despedirEnsambladores();
    }//GEN-LAST:event_despedirEnsambladoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window(s).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContratarB;
    private javax.swing.JButton DespedirB;
    private javax.swing.JButton DespedirPPantalla;
    private javax.swing.JButton DespedirPSD;
    private javax.swing.JButton Start1;
    private javax.swing.JLabel botones;
    private javax.swing.JLabel consolas;
    private javax.swing.JButton contrararPpantallas;
    private javax.swing.JButton contratarPJoystick;
    private javax.swing.JButton contratarPSD;
    private javax.swing.JButton despedirEnsambladores;
    private javax.swing.JButton despedirJoystick;
    private javax.swing.JLabel dias;
    private javax.swing.JLabel ensambladores;
    private javax.swing.JLabel gerente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jefe;
    private javax.swing.JLabel jefe2;
    private javax.swing.JLabel joysticks;
    private javax.swing.JLabel maxBotones;
    private javax.swing.JLabel maxEnsambladores;
    private javax.swing.JLabel maxJoysticks;
    private javax.swing.JLabel maxPBotones;
    private javax.swing.JLabel maxPJoystick;
    private javax.swing.JLabel maxPLectoresSD;
    private javax.swing.JLabel maxPPantallas;
    private javax.swing.JLabel maxPantallasN;
    private javax.swing.JLabel maxPantallasT;
    private javax.swing.JLabel maxSD;
    private javax.swing.JLabel pantallasN;
    private javax.swing.JLabel pantallasT;
    private javax.swing.JLabel productorBotones;
    private javax.swing.JLabel productorJoystick;
    private javax.swing.JLabel productorPantallas;
    private javax.swing.JLabel productorSD;
    private javax.swing.JLabel tarjetasSD;
    // End of variables declaration//GEN-END:variables
}
